[build]
  publish = "."

[[redirects]]
  from = "/login"
  to = "/public/product/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/product/*"
  to = "/public/product/:splat"
  status = 200
  force = true
